### ISSUE TITLE
New crate versions

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/traits#43]
Migrating to 2018 edition is a long overdue and since it's a good chance to introduce breaking changes, I propose to use this issue to discuss them. Right now I have the following list of changes:

- [x] Migrate to 2018 edition and bump MSRV to ~~1.36~~ 1.41 (needed for `generic-array` v0.14)
- [x] Update `generic-array` to ~~v0.13~~ v0.14.
- [x] Release `crypto-mac v0.8` which uses `subtle v2`. (see #35)
- [x] Rename `crypto_mac::Mac::input` and `digest::Digest::input` methods to `update`.
- [x] Rename `digest::Input` to `digest::Update`.
- [x] Remove `digest::Reset` trait in favor of reworked `FixedResult` trait. See this [comment](https://github.com/RustCrypto/hashes/issues/86#issuecomment-509045192).
- [x] Deprecate `block-cipher-trait` and use `block-cipher` crate instead #28.
- [x] Introduce a new `NewBlockCipher` trait (#164).
- [x] Add `stream_cipher::FromBlockCipher` trait.
- [x] Add [`impl_write!`](https://github.com/RustCrypto/traits/blob/master/digest/src/lib.rs#L127) macro to `crypto-mac`.
- ~~Find solution for buffer-to-buffer cipher operations #31~~
- ~~Add `try_new` methods~~ (closed as wontfix, see #47)
- [x] Rename `MacResult` type to something like `Code`/`Output` and rename `code` method to `into_bytes` for consistency with the `universal-hash` crate.
- ~~Add macro for implementing `io::Write` to `crypto-mac` similarly to the `digest` crate.~~ (dup of above)
- [x] Bump `opaque-debug` to v0.2
- ~~Support variable length AEAD Nonces #65~~ (EDIT: solved by making ciphers generic over their `NonceSize`)
- [x] Rename `crypto_mac::Mac::result`, `digest::Digest::result`, and `universal_hash::UniversalHash::result` to `::finalize` or `::finish`

I may have forgotten some changes I had in mind. Feel free to suggest other public API changes.

**Comment by tarcieri** [comment]
To me the common terminology is Initialize-Update-Finalize (IUF) and `update` would make sense IMO

**Comment by newpavlov** [comment]
@burdges 
Can you provide examples of other libraries which use `input`? I would also prefer to keep the name to limit breakage, but it looks like it's fairly uncommon name for the method across hashing libraries.

**Comment by burdges** [comment]
After a quick look, it appears terms like input and add are common only for hashmaps, etc., and update wins with it being the term from OpenSSL, libsodium, and Python, while Go and libgcrypt use write, and operators overloading being common too.  

We'd use [`core::io::Write`](https://github.com/rust-lang/rust/issues/48331) if it existed, but otherwise whatever.  :)

**Comment by newpavlov** [comment]
BTW maybe we should bump MSRV to 1.36? It will allow us to use `alloc` without compatibility workarounds.

**Comment by akhilles** [comment]
Can `block-cipher` traits support IV non-reuse? With the current API, IV has to be introduced in the cipher’s constructor. We should be able to specify the IV in the encryption call instead.

**Comment by newpavlov** [comment]
Maybe you mean `stream-cipher` or `block-modes`? IIRC the main reason for moving IV to `new` was interaction with seeking. Also it was more consistent with other traits.

What is motivation for such change in your opinion, assuming we will get the `FromBlockCipher` trait?

**Comment by akhilles** [comment]
@newpavlov I was referring specifically to the `BlockMode` trait. Currently, in order to use a different IV for each encryption, you have to reconstruct the cipher object which results in poor performance. This encourages the re-use of IVs, which is bad.

Instead, I think it's reasonable to have an API that allows you to specify IV for each encryption request. I believe `mbedtls` offers a similar API.

**Comment by tarcieri** [comment]
@akhilles I'd be all about finding misuse resistant nonce management strategies at the abstraction level of [AEAD crates](https://github.com/rustcrypto/aeads), but at the level of block ciphers, concerns like this ring hollow to me:

> Currently, in order to use a different IV for each encryption, you have to reconstruct the cipher object which results in poor performance. This encourages the reuse of IVs.

Perhaps we haven't found a way to position block mode crates correctly, but here's how I would advertise them:

- WARNING: Dangerous "hazmat" materials with "subtle" properties
- Prone to explode in your face
- Really you should use [AEADs](https://github.com/rustcrypto/aeads) if you want safety

**Comment by akhilles** [comment]
@tarcieri AES-CBC w/o auth tag and w/o reusing IVs is a perfectly legitimate (and common) use case. There is no API that supports it in this project.

What are the downsides to allowing IV to be provided in the encryption call?

**Comment by newpavlov** [comment]
@akhilles 
I am not sure if you proposal will work well with the stateful approach which we use for block modes API (see `encrypt_blocks` and `decrypt_blocks` methods). I think `FromBlockCipher` trait should work fine here. For example, instead of:
```rust
type AesCbc = Cbc<Aes128>;
let cipher = AesCbc::new(key);
let res1 = cipher.encrypt(buf1, pos1, iv1)?;
let res2 = cipher.encrypt(buf2, pos2, iv2)?;
```
You will write:
```rust
let cipher = Aes128::new(key);
let res1 = Cbc::from_cipher(cipher, iv1).encrypt(buf1, pos1)?;
let res2 = Cbc::from_cipher(cipher, iv2).encrypt(buf2, pos2)?;
```
It's a bit more verbose, but efficiency-wise it will be equivalent. Also it will be more flexible, since `encrypt_blocks` and `decrypt_blocks` will be left intact.

**Comment by akhilles** [comment]
@newpavlov, I'd be perfectly happy with `FromBlockCipher`. I just wanted a way to change IV without going through round key generation.

Is there a PR open for the `FromBlockCipher` trait or is it still in the design phase?

**Comment by shepmaster** [comment]
> * Update `generic-array` to v0.13.

> Since it's a breaking change [comment](https://github.com/RustCrypto/utils/issues/32#issuecomment-535190661)

I don't know enough about the changes in generic-array 0.12 -> 0.13, but please remember that you can use version ranges if *this crate* doesn't use any changed APIs. For example, [xxhash can work with basically any version of rand](https://github.com/shepmaster/twox-hash/blob/5c9a4690f576a20280a9ecbc4cbdc3ab2fff26e2/Cargo.toml#L18) because it only uses `rand::{thread_rng, Rng}`.

**Comment by AxelNennker** [comment]
Can I bribe one of RustCrypto Developers with a beer next time somebody is in Berlin, Germany to do the `cargo publish`? Sorry, if this offer is not appropriate.

**Comment by tarcieri** [comment]
Unfortunately I don't have access to release new crate versions, but in the meantime we can do the work enumerated in this issue

**Comment by frol** [comment]
@newpavlov Is there a chance to have some progress here? :eyes:

**Comment by tarcieri** [comment]
I reached out to @newpavlov a few times now but haven't been able to get ahold of him.

**Comment by tarcieri** [comment]
For people interested in new crate releases, I've made a contingency plan for publishing new versions provided @newpavlov doesn't return to do so: #102 

It involves picking new names for each of the crates, which is less than ideal. I'm curious what people have to think about this approach.

**Comment by kpcyrd** [comment]
This would cause significant load on the debian-rust team because we need to get each package re-approved. Preferably crates that are this central in the rust eco system would have multiple maintainers with publish privileges.

Maybe this is something we can raise awareness about, collect instructions on how to find backup maintainers that are trusted in the community and encourage people to have multiple people with publish permissions (and/or permissions to assign more uploaders).

**Comment by tarcieri** [comment]
@kpcyrd we were in the progress of migrating all of these crates to teams-based permissions rather than individual publishers, but that work was never completed, and at present @newpavlov has sole access to many of the crates.

I'm not in a hurry to do any of this so I'll wait until at least Q3 2020 before actually thinking about moving forward with it.

**Comment by tarcieri** [comment]
Ok, I have access to release all of the trait crates 🎉 

It seems there's some work itemized in the description above which I think it'd be good to do before cutting any releases, but I think it's now possible to get this done this weekend.

**Comment by tarcieri** [comment]
One other API suggestion I have is along with the `Output` changes, going with the "Initialize-Update-Finalize" (IUF) nomenclature and changing the `result` methods of `crypto-mac`, `digest`, and `universal-hash` to `finalize`.

**Comment by tarcieri** [comment]
Regarding this issue:

> Rename MacResult type to something like Code/Output and rename code method to into_bytes for consistency with the universal-hash crate.

We could consistently use `Output` across the board for `crypto-mac`, `digest`, and `universal-hash` if that sounds good. Otherwise I think the most common name for MAC output is `Tag` (which is what is used in most of the AEAD implementations).

**Comment by tarcieri** [comment]
As it's been a long time since there's been a release of the various crates in this repo, I'd like to do one ASAP.

I've addressed a number of issues today (see checkboxes in the OP). The remaining things I'd personally like to do before cutting a release:

- Add `NewBlockCipher`
-  Add impl_write! macro to crypto-mac
- Rename `block-cipher-trait` to `block-cipher` when @newpavlov gives me access to the [`block-cipher` crate](https://crates.io/crates/block-cipher)  #28 
- Split` Aead(Mut)` from `Aead(Mut)InPlace`, making the in-place APIs object safe #70. There's an open PR for this: #120 

Everything else which isn't already complete I'd personally like to punt on as I think upgrading `generic-array` is a big blocker for several people (including myself) right now.

My personal plan would be to cut some prerelease versions of these crates tomorrow (May 24th) and try upgrading the existing implementations which consume them and look for any showstopper issues, if that sounds good to everyone else.

**Comment by tarcieri** [comment]
Something else I think might be helpful for any crates which use `generic-array`:

The `heapless` crate [re-exports `generic_array::typenum::consts` from the toplevel](https://github.com/japaric/heapless/blob/ab9f251/src/lib.rs#L79):

https://docs.rs/heapless/0.5.5/heapless/consts/index.html

I think that helps a lot in terms of the API ergonomics.

**Comment by tarcieri** [comment]
I went ahead and added `generic_array::typenum::consts` re-exports ala the `heapless` crate in #123

**Comment by nickray** [comment]
Looking forward to removal of `new` from `block-cipher`, in context of hw AES.

**Comment by tarcieri** [comment]
Yes, exactly. In fact all of the traits in this repo now have a corresponding `New*` trait which allows any primitive to have a hardware-backed key.

Also I should probably announce that almost all of the repos in this project have been updated and bumped to a `-pre` version. I haven't done any crate releases yet, but you can pull in the prereleases from git ala:

https://github.com/RustCrypto/AEADs/blob/master/Cargo.toml#L13-L27

**Comment by nickray** [comment]
Great. Yeah I'm working against `0.7.0-pre` of `block-cipher`.

**Comment by nickray** [comment]
Also regarding `block-cipher` (let me know if I should open a separate issue), it would be quite convenient if `encrypt_block` and `decrypt_block` could assume some specified alignment (enforced e.g. via the `aligned` crate) to operate on (for instance 32-bit aligned). Is this thinkable, or am I missing some way to do this with the existing trait?

**Comment by tarcieri** [comment]
That's probably worth a separate issue.

The problem right now is how you tie an alignment to the block size.

One option is to change `BlockSize` to an associated `Block` type which has a well-known `#[repr(align(...))]`

**Comment by AxelNennker** [comment]
would you please consider doing 
"Release crypto-mac v0.8 which uses subtle v2. (see #35)"?

**Comment by tarcieri** [comment]
@AxelNennker we're getting ready to do a release of all of these crates. Hopefully later this week.

One remaining item I think it's worth considering is moving all the crates closer to Initialize-Update-Finalize (IUF) nomenclature (including `crypto-mac`) by renaming the `result()` method to `finalize()` or `finish()`.

Several crates (including MAC implementations) use the `finalize()` name internally.

I'll go ahead and add a checkbox for this at the top.

**Comment by tarcieri** [comment]
@newpavlov are there any additional items you think are showstoppers for another release?

**Comment by tarcieri** [comment]
I took a look at renaming `result` => `finalize` and it seems there are many more cases that would need to be updated for consistency, namely:

https://docs.rs/digest/0.8.1/digest/trait.FixedOutput.html
https://docs.rs/digest/0.8.1/digest/trait.ExtendableOutput.html
https://docs.rs/digest/0.8.1/digest/trait.VariableOutput.html

**Comment by tarcieri** [comment]
I opened #161 which renames the `result` methods to `finalize`.

If that looks good to everyone, I'll do another pass over all of the implementations to update them.

After that there are a few small remaining things I'd like to clean up, but that said, I think we're good for a release of many of the crates later this week.

**Comment by newpavlov** [comment]
It would be nice to do the `digest::Reset` rework and solve the buffer-to-buffer issue. Otherwise at the moment I don't have any API changes in mind not listed in the OP.

**Comment by tarcieri** [comment]
#31 (buffer-to-buffer cipher operations) seems a bit involved and like it could use some more discussion and exploration of possible API designs. I'd rather punt on it for this release so it doesn't hold the releases of other crates back.

I can take a look at implementing the `FixedOutput` changes proposed in https://github.com/RustCrypto/hashes/issues/86

**Comment by tarcieri** [comment]
I took a look at https://github.com/RustCrypto/hashes/issues/86 and I'm a little bit confused by it (particularly `_fixed_result_core`).

I wonder if perhaps another trait and a blanket impl are in order?

**Comment by newpavlov** [comment]
The idea is that we use a quasi-private method, which could leave hash instance in an incorrect state (well, strictly speaking it's still correct, but should not be used in practice) by passing `false` to `reset`. I will try to prepare PRs with those changes. I don't think we need an additional trait here, since it can be applied to all current implementors of `FixedOutput` directly and I think should be applicable for potential hardware-based solutions as well.

**Comment by tarcieri** [comment]
Sounds good.

In the meantime, I think the following crates can be published:

- `aead` v0.3.0
- `block-cipher` v0.7.0 (I kept the versioning consistent with `block-cipher-trait`)
- `crypto-mac` v0.8.0
- `stream-cipher` v0.4.0
- `universal-hash` v0.4.0

(`signature` can also get a bump, but it depends on `digest`)

**Comment by newpavlov** [comment]
Sounds good!

**Comment by tarcieri** [comment]
I've released new versions of the `aead`, `block-cipher`, `crypto-mac`, `stream-cipher`, and `universal-hash` crates as outlined above.

**Comment by tarcieri** [comment]
I took a stab at addressing https://github.com/RustCrypto/hashes/issues/86 in this PR:

https://github.com/RustCrypto/traits/pull/180/files

It's slightly different from what @newpavlov originally proposed, but eliminates the need to have an "internal" method on the trait.

**Comment by burdges** [comment]
Also https://github.com/rust-lang/rfcs/pull/2884

**Comment by tarcieri** [comment]
@burdges cool, nice to see progress is being made on RVO

**Comment by tarcieri** [comment]
Alright, with #183 and #184 landed I think we're ready to cut a new release of `digest`.

I'll go ahead and update https://github.com/RustCrypto/hashes first to make sure there's nothing we overlooked.

**Comment by shepmaster** [comment]
For future reference, switching from a generic to `impl trait` is generally a step back, [as there's no way to use a turbofish with `impl trait`](https://stackoverflow.com/q/47514930/155423).

**Comment by tarcieri** [comment]
@shepmaster did you actually take a look at the relevant changes? They're all `AsRef` coercions. For these particular use cases, `impl Trait` is much more readable, and I don't think there's any potential turbofish use cases.

**Comment by shepmaster** [comment]
I am upgrading a crate to support 0.9, so, yes, I am looking at the changes. My comment is applicable because you cannot know all the call sites. Maybe you made the decision on purpose and with full knowledge of the effects, I don't know. All I can do is transfer knowledge in case you didn't already know.

**Comment by tarcieri** [comment]
For these particular cases, impl Trait in the argument position should be syntactic sugar for the generic parameter. If you have a use case where that isn’t so, I’d be curious to see it, however the only case I can think of is one where you were turbofishing a generic parameter which is now no-longer necessary. That said, I’d be curious to know specific examples where this is actually problematic from the caller’s side.
