### ISSUE TITLE
aead v0.4.0 release

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/traits#523]
The `aead` crate is fairly self-contained in that it doesn't have dependencies on other RustCrypto traits.

I've landed everything I would want to get in a release. This includes:

- [x] #436: `stream` module
- [x] #508: extract `AeadCore` trait
- [x] #512: use `new_from_slice` naming convention
- [x] #513: add `generate_key` method to `New*` traits 
- [x] #514: disable alloc by default
- [x] #522: bump `heapless` dependency to v0.6

Is there anything else we should do before a final release?

**Comment by tarcieri** [comment]
Note: I plan on cutting a release of this in the next few days unless there are any showstopper issues.

**Comment by tarcieri** [comment]
#259 seems like a potentially relevant issue, although I'm not sure it's really necessary.

I'll leave some comments on the issue, but don't consider it a release blocker.

**Comment by tarcieri** [comment]
Released in #526
